# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    # To upgrade hooks run: `prek autoupdate --freeze`
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c  # frozen: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/crate-ci/typos
    rev: 53821664afd79bb88fcdd22fdc2f49d8d3f6cac9  # frozen: v1
    hooks:
      - id: typos

  - repo: local
    hooks:
      - id: local-just--fmt
        name: auto reformat justfile
        entry: just --fmt
        language: system
        pass_filenames: false

      - id: local-just--evaluate
        name: check justfile syntax
        entry: just --evaluate
        language: system
        pass_filenames: false
