[project]
name = "project"
version = "0.1.0"
description = "Default template for PDM package"
authors = [
    {name = "Waket Zheng",email = "waketzheng@gmail.com"},
]
dependencies = [
    "fastapi>=0.141.1",
    "uvicorn>=0.52.3",
]
requires-python = "==3.12.*"
readme = "README.md"
license = {text = "MIT"}

[tool.uv]
package = false

[tool.pdm]
distribution = false

[dependency-groups]
dev = [
    "asynctor[testing]>=0.14.0",
    "coverage>=7.15.4",
    "pytest>=9.1.1",
]
