# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: ci

on:
  push:
    branches: [ "main", "dev" ]
    paths-ignore:
      - "docs/**"
      - "*.md"
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - "docs/**"
      - "*.md"

permissions:
  contents: read

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: [3.12]
    steps:
      - uses: actions/checkout@v7
        with:
          ssh-key: ${{ secrets.DEPLOY_KEY }}
          submodules: true
      - name: Setup SSH key for manual git clone
        shell: bash
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
          git config --global core.sshCommand "ssh -o StrictHostKeyChecking=no"
      - name: Clone tests by SSH
        run: |
          git clone git@github.com:waketzheng/justfile-test
          mv justfile-test/tests .
      - name: Setup Python
        id: setup-python
        uses: actions/setup-python@v7
        with:
          python-version: ${{ matrix.python-version }}
          allow-prereleases: true
      - uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
        with:
          enable-cache: true
          version: "0.12.3"
          cache-dependency-path: |
            pyproject.toml
            uv.lock
      - name: Setup just by uv
        run: |
          uv tool install rust-just
      - name: Setup PDM by uv
        run: |
          uv tool install pdm --with pdm-plugin-i
          pdm config check_update false
          pdm config use_uv true
      - name: Setup Prek by uv
        run: |
          uv tool install prek
      - name: Check justfile syntax
        run: |
          mv justfile justfile.bak
          cp sample.justfile justfile
          prek run --all-files
          cp justfile.bak justfile
          prek run --all-files
          just
      - name: Check justfile import
        run: |
          cd tests/my-project
          cp ../../sample.justfile justfile
          just
          just venv
          python -c "import shutil;from pathlib import Path;f='README.md';Path(f).exists() or shutil.copy('../'+f, '.')"
          just install
          just add anyio
          just add --dev pytest coverage
          just remove --dev coverage
          just up

          cd ../app-project
          cp ../../sample.justfile justfile
          just init ssh
          just
          just venv
          just install
          just test

          cd ../project
          cp ../../sample.justfile justfile
          just init
          just
          just venv
          just install
          just test

          cd ../src-project
          cp ../../sample.justfile justfile
          just init ssh
          just
          just venv
          uvx pip-conf-mirror --uv qh
          uv lock
          python -c "from pathlib import Path;f=Path('uv.lock');s=f.read_text();assert 'pypi.org' in s"
          just install
          python -c "from pathlib import Path;f=Path('uv.lock');s=f.read_text();assert 'pypi.org' in s"
          uvx --from fast-dev-cli fast pypi --reverse --quiet
          python -c "from pathlib import Path;f=Path('uv.lock');s=f.read_text();assert 'pypi.org' not in s"
          just install
          python -c "from pathlib import Path;f=Path('uv.lock');s=f.read_text();assert 'pypi.org' not in s"
